### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#364]
- [x] give deluge some love. (local torrent, magnet and torrent link, set speed, pause etc) https://github.com/Hellowlol/HTPC-Manager/issues/19 in progress
- [x] sabnzbd add pause for x minutes
- [x] sab add remove all/failed etc. https://github.com/Hellowlol/HTPC-Manager/issues/318
- [x] sab, manually added nzbs shoud have prio high.
- [x] stats remove shell access and expose the script without --shell
- [x] vnstat: be table to set a default interface for the graphs (have to be done in vnstat.conf today.) https://github.com/Hellowlol/HTPC-Manager/issues/357
