### ISSUE TITLE
Ideas / todo

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/HTPC-Manager#4]
- [ ] add more api stuff to sr.  edit show, backlog, change episode search modal. (when ever the api is fixed) 
- [ ] ipcamera 3
- [ ] add a trakt module with send to sr, sb, sonarr and cp.
- [ ] add mb3?
- [x] Improve the dash?
- [ ] xbmc module improvements, use ws to send key, sources, add episode modal and season.
- [ ] make a stat process modal 
- [ ] Make about tab with sys info etc
- [ ] Upload log to pastebin, need to get apikey, max 10 MB logfiles.
- [x] add reset hard to git updater
- [x] Updater need some work so changing branches work.
- [x] move create cert ssl activation after os.path.exists.
- [ ] ban ip if more then x login attempts to protect against brute force? Worth the effort, since it's a false sense of security? 
- [x] add option for proxy headers.
- [x] add a option git clean atm its just htpc.debug.
- [x] add failed and successfull login attempts to the log.
- [x] add drag drop editque to SAB remember to add handle cus of touchscreens
- [ ] add edit que to nzbget waiting for v15 add handle!
- [x] Fix settings save. window.location.reload(true) should be inside the post and only fired is post returns success
- [x] sourceupdater branch should be verfied if the version file has a sha.
- [ ] Add more spinners
- [x] Replace bootstrap icon with client icon in nzb search and torrent search
- [x] add argsparse for python 2.6 users
- [ ] add new screenshots
- [x] autoupdater
- [x] Add set speed to transmission
- [x] Add trending/suggestions to cp and sr (need to make pr to sr about it first)
- [ ] dont run plex headers unless username password.
- [ ] fix qbt so it dosnt block htpc manager if error
- [x] username and password set in the general tab should overwrite db even if user name is unique
- [x] fix/disable annoying branch notification in the settings page when running from source
- [x] fix error welcome msg if no enabled module in dash
- [x] headphones
- [x] remove Fenopy as its closed :(
- [x] figure out why im.thumbnail fails. Works in script.
- [x] fix update button inside update footer
- [x] add container-fluid to sr view, check sonar aswell
- [ ] increse size on cached images cus of fluid.
- [x] move commonly used stuff to helpers like wake, get image etc.
- [ ] rename htpc debug to dev, add guidelines for reporting bugs,
- [ ] minify and combine css, js if not htpc debug?
- [ ] add ptp and kat to torrent search?
- [x] Fix typo in stat module
- [x] Make sure each exposed url has @require()
- [x] upgrade mako
- [x] add -fluid to the update notification bar.
- [ ] remove before span spinner on stats page.
- [x] fix github link img end tag
- [x] add auth access to the new links
- [ ] fix holder.run in xbmc addons.
- [ ] change line height in navbar.

**Comment by Snipees** [comment]
Since I started using this product, I imagined what could be the perfect interface and I think that a simplified interface, smoother, better organized and more interactive would be 'user-friendly' to my family members and will make more sense for them.

Instead of the current sections, the user interface could be organized around sections: Dashboard, OnDesk, Wanted, InProgess, AddContent, Monitor ; rewritten this way:

- A **[Dashboard]**, similar to the current one, with display of current downloads.

- Section **[AddContent]** interactive, step by step:

	1. What would you download? (movies, TV shows, music albums, ...)
		> To know who to call? (cp, sb, hp, ...) and what folder to download content.

	2. Would you like to:
		- Search for a title?
			> Will be using cp, sb or hp depending on the previous answer.

		- Manually download the torrent?
			> As currently proposed in Transmission interface, but could also accept local .torrents files.

		- Manually download the newsgroup file?
			> I never used newsgroups, so I don't know how it's working.

		- Download manually from a file hoster?
			> Will be using PyLoad.

	3. Cell to research/adding the desired content.
		> Depending on the previous answer, displays a dedicated cell.

	4. Display the result of the research or display the file upload interface.
		> Displays search results if title search, otherwise display current download (torrent, newsgroups or file hoster)

- Section **[InProgress]** shows downloads in progress, organized by tabs for: torrents, newsgroups, file hosting
	> Similar to existing interfaces.


- Section **[Wanted]** displays the desired content in waiting, organized by tabs: films, series TV, music artists.
	> Similar to existing interfaces.


- Section **[OnDesk]** displays the contents of XBMC/Plex organized by tabs (similar to the current display) and offers possibility to streaming or local download of contents.
	> Possible tracks: cakebox-light (github).


- Section **[Monitor]** displays the server informations, more comprehensive than the current display.
	> Possible tracks: seedbox-manager (github) ezservermonitor-web (github).





Otherwise, here are some more reasonable suggestions: ^^

- For the Dashboard: display current downloads.
- For Transmission: allow downloading from a local .torrent file
- For Transmission: add a combo choice of the category of file: movies, TV shows, music. (to select desired folder to download)
- Integration of PyLoad with an interface similar to the current Transmission interface 
- Added a section for local download of content (see cakebox-light (github))
- Upgrades of the Statistics section (see seedbox-manager (github) ezservermonitor-web (github))

**Comment by Hellowlol** [comment]
@Snipees Thanks for your requests, its obvious that you have used alot of time and effort on it! 

A [Dashboard], similar to the current one, with display of current downloads. 
**There will be some sort of current clients, like sab idle speed 0, nzbget idle speed 0, transmission seeding 100 kbs etc, i havnt decided if it gonna take the torrents aswell, it would be alot work.**

Section [AddContent] interactive, step by step:
**I like the idea, i can see it has some use for kids etc. But i will not work on this request since i dont have use for it and it will be more clicks.**

* Section [InProgress] shows downloads in progress/finished, organized by tabs for: torrents, newsgroups, file hosting.
**I will not work on this. There is already a latest download for several clients.**

* Section [Wanted] displays the desired content in waiting, organized by tabs: movies, TV shows, music artists.
**I will not work on this.**

* Section [Monitor] displays the server informations, more comprehensive than the current display.
** I like the idea, i would like grap more info about the system like cpu type etc, but i havnt found a cross platform way to do this. Regarding the graphs, dunno, maybe, im not gonna discard it atleast. **

Otherwise, here are some more reasonable suggestions: ^^

For the Dashboard: display current downloads.
**Ill keep it in mind. PRS welcome**
For Transmission: allow downloading from a local .torrent file
 **Accepted, i have no eta**
For Transmission: add a combo choice of the category of file: movies, TV shows, music. (to select desired folder to download)
**Accepted if supported by the api**
Integration of PyLoad with an interface similar to the current Transmission interface
**I will not work on this. But PRS are welcome**
Added a section for local download of content (see cakebox-light (github))
**Maybe, PRS welcome**
Upgrades of the Statistics section (see seedbox-manager (github) ezservermonitor-web (github))
**Maybe, PRS welcome**

**Comment by Hellowlol** [comment]
I locked this since its intended to be a place where I write down ideas, thing that I consider to add to HTPC manager. Please made a new issue for each future request/issue
